DEFAULT_MODEL_PATH = "CNN_model.h5"
DEFAULT_DATA_ROOT = "Dataset"
DEFAULT_STREAMLIT_TEMP_DIR = "temp"

DEFAULT_INPUT_SHAPE = (128, 128, 3)
DEFAULT_TARGET_SIZE = (128, 128)

DEFAULT_TRAIN_EPOCHS = 10
DEFAULT_TRAIN_BATCH_SIZE = 32
DEFAULT_TRAIN_STEPS_PER_EPOCH = 200
DEFAULT_TRAIN_VAL_STEPS = 50
DEFAULT_TRAIN_MAX_FRAMES = 16
DEFAULT_TRAIN_OUTPUT = "models/xception_model.h5"

DEFAULT_EVAL_MAX_FRAMES = 64
DEFAULT_EVAL_BATCH_SIZE = 32
DEFAULT_EVAL_OUT_PREFIX = "scores"
DEFAULT_EVAL_AGG_METHOD = "mean"
DEFAULT_EVAL_THRESHOLD = 0.5
DEFAULT_EVAL_TOP_K = 3
DEFAULT_EVAL_GRADCAM_OUT = "gradcam"

DEFAULT_PRED_THRESHOLD = 0.5
DEFAULT_DETECTOR_TYPE = "mtcnn"
DEFAULT_DETECTOR_PADDING = 0.2

LABEL_REAL = "Real"
LABEL_FAKE = "Fake"

CLASS_REAL_NAME = "real"
FACE_DETECTOR_RETINAFACE = "retinaface"
FACE_DETECTOR_MTCNN = "mtcnn"

SERVE_APP_TITLE = "DeepFake Detection API"
SERVE_HOST = "0.0.0.0"
SERVE_PORT = 8000
